CREATE TABLE RECOMMENDATION 
(
  ORDER_ID               INTEGER,
  BOOK_ID                INTEGER   
);

ALTER TABLE RECOMMENDATION ADD CONSTRAINT FK_RECOMMENDATION_ORDER_ID 
  FOREIGN KEY (ORDER_ID) REFERENCES TABLE_ORDER
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE RECOMMENDATION ADD CONSTRAINT FK_RECOMMENDATION_BOOK_ID
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

CREATE TABLE PROVIDER
(
  ID                            INTEGER         NOT NULL,
  TITLE                         VARCHAR(   100)  COLLATE NONE
);

CREATE TABLE SUPPLY
(
  ID                            INTEGER         NOT NULL,
  PROVIDER_ID                      INTEGER
);

CREATE TABLE STOCK
(
  ID                            INTEGER         NOT NULL,
  TITLE                         VARCHAR(   100)  COLLATE NONE
);

CREATE TABLE COMPOSITION_OF_SUPPLY
(
  SUPPLY_ID                            INTEGER         NOT NULL,
  BOOK_ID                            INTEGER         NOT NULL,
  STOCK_ID                            INTEGER         NOT NULL,
  NUMBER                            INTEGER         NOT NULL
);

CREATE TABLE COMPOSITION_OF_STOCK
(
  BOOK_ID                            INTEGER         NOT NULL,
  STOCK_ID                            INTEGER         NOT NULL,
  NUMBER                            INTEGER         NOT NULL
);

ALTER TABLE PROVIDER ADD CONSTRAINT PK_PROVIDER PRIMARY KEY
  (ID);
  
ALTER TABLE SUPPLY ADD CONSTRAINT PK_SUPPLY PRIMARY KEY
  (ID);
  
ALTER TABLE STOCK ADD CONSTRAINT PK_STOCK PRIMARY KEY
  (ID);
  
ALTER TABLE SUPPLY ADD CONSTRAINT FK_PROVIDER_ID 
  FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE COMPOSITION_OF_SUPPLY ADD CONSTRAINT FK_SUPPLY_ID
  FOREIGN KEY (SUPPLY_ID) REFERENCES SUPPLY
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE COMPOSITION_OF_SUPPLY ADD CONSTRAINT FK_SUP_BOOK_ID
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE COMPOSITION_OF_SUPPLY ADD CONSTRAINT FK_SUP_STOCK_ID
  FOREIGN KEY (STOCK_ID) REFERENCES STOCK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE COMPOSITION_OF_STOCK ADD CONSTRAINT FK_STOCK_STOCK_ID
  FOREIGN KEY (STOCK_ID) REFERENCES STOCK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE COMPOSITION_OF_STOCK ADD CONSTRAINT FK_STOCK_BOOK_ID
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;