/*******************************************************************************
 * Selected metadata objects
 * -------------------------
 * Extracted at 10.10.2016 9:55:52
 ******************************************************************************/

/*******************************************************************************
 * Tables
 * ------
 * Extracted at 10.10.2016 9:55:52
 ******************************************************************************/

CREATE TABLE TABLE_AUTHOR 
(
  ID                INTEGER         NOT NULL,
  "NAME"              VARCHAR(   100)  COLLATE NONE
);
CREATE TABLE TABLE_BOOK 
(
  ID                            INTEGER         NOT NULL,
  TITLE                         VARCHAR(   100)  COLLATE NONE,
  PUBLISH_HOUSE_ID              INTEGER,
  DECRIPTION                    VARCHAR(   200)  COLLATE NONE,
  YEAR_ISSUE                    INTEGER,
  RATING                          FLOAT,
  PRICE                           FLOAT
);
CREATE TABLE TABLE_BOOK_AUTHORS 
(
  AUTHOR_ID              INTEGER,
  BOOK_ID                INTEGER
);
CREATE TABLE TABLE_BOOK_CATEGORY 
(
  CATEGORY_ID              INTEGER,
  BOOK_ID                  INTEGER
);
CREATE TABLE TABLE_BOOK_REWARDS 
(
  REWARD_ID                INTEGER,
  BOOK_ID                  INTEGER,
  YEAR_REWARD              INTEGER
);
CREATE TABLE TABLE_CATEGORY 
(
  ID                INTEGER         NOT NULL,
  "NAME"              VARCHAR(   100)  COLLATE NONE
);
CREATE TABLE TABLE_CLIENT 
(
  ID                 INTEGER         NOT NULL,
  "NAME"              VARCHAR(   100)  COLLATE NONE,
  EMAIL              VARCHAR(   100)  COLLATE NONE,
  PASS               VARCHAR(   100)  COLLATE NONE,
  PHONE              VARCHAR(   100)  COLLATE NONE
);
CREATE TABLE TABLE_ORDER 
(
  ID                      INTEGER         NOT NULL,
  CLIENT_ID               INTEGER,
  DATE_ORDER                 DATE,
  PRICE                     FLOAT
);
CREATE TABLE TABLE_ORDER_LIST 
(
  ORDER_ID              INTEGER,
  BOOK_ID               INTEGER,
  PRICE                   FLOAT,
  NUMBER                INTEGER
);
CREATE TABLE TABLE_PUBLISHING_HOUSE 
(
  ID                INTEGER         NOT NULL,
  "NAME"              VARCHAR(   100)  COLLATE NONE
);
CREATE TABLE TABLE_REVIEWS 
(
  ID                       INTEGER         NOT NULL,
  CLIENT_ID                INTEGER,
  BOOK_ID                  INTEGER,
  TEXT                     VARCHAR(   250)  COLLATE NONE,
  DATE_REVIEW                 DATE
);
CREATE TABLE TABLE_REWARDS 
(
  ID                INTEGER         NOT NULL,
  "NAME"              VARCHAR(   100)  COLLATE NONE
);
/*******************************************************************************
 * Primary Key Constraints
 * -----------------------
 * Extracted at 10.10.2016 9:55:52
 ******************************************************************************/

ALTER TABLE TABLE_AUTHOR ADD CONSTRAINT PK_TABLE_AUTHOR PRIMARY KEY
  (ID);

ALTER TABLE TABLE_BOOK ADD CONSTRAINT PK_TABLE_BOOK PRIMARY KEY
  (ID);

ALTER TABLE TABLE_CATEGORY ADD CONSTRAINT PK_TABLE_CATEGORY PRIMARY KEY
  (ID);

ALTER TABLE TABLE_CLIENT ADD CONSTRAINT PK_TABLE_CLIENT PRIMARY KEY
  (ID);

ALTER TABLE TABLE_ORDER ADD CONSTRAINT PK_TABLE_ORDER PRIMARY KEY
  (ID);

ALTER TABLE TABLE_PUBLISHING_HOUSE ADD CONSTRAINT PK_TABLE_PUBLISHING_HOUSE PRIMARY KEY
  (ID);

ALTER TABLE TABLE_REVIEWS ADD CONSTRAINT PK_TABLE_REVIEWS PRIMARY KEY
  (ID);

ALTER TABLE TABLE_REWARDS ADD CONSTRAINT PK_TABLE_REWARDS PRIMARY KEY
  (ID);

/*******************************************************************************
 * Foreign Key Constraints
 * -----------------------
 * Extracted at 10.10.2016 9:55:52
 ******************************************************************************/

ALTER TABLE TABLE_BOOK ADD CONSTRAINT FK_TABLE_BOOK 
  FOREIGN KEY (PUBLISH_HOUSE_ID) REFERENCES TABLE_PUBLISHING_HOUSE
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_AUTHORS ADD CONSTRAINT FK_TABLE_BOOK_AUTHORS 
  FOREIGN KEY (AUTHOR_ID) REFERENCES TABLE_AUTHOR
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_AUTHORS ADD CONSTRAINT FK_TABLE_BOOK_AUTHORS_TWO 
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_CATEGORY ADD CONSTRAINT FK_TABLE_BOOK_CATEGORY 
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_CATEGORY ADD CONSTRAINT FK_TABLE_BOOK_CATEGORY_TWO 
  FOREIGN KEY (CATEGORY_ID) REFERENCES TABLE_CATEGORY
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_REWARDS ADD CONSTRAINT FK_TABLE_BOOK_REWARDS 
  FOREIGN KEY (REWARD_ID) REFERENCES TABLE_REWARDS
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_BOOK_REWARDS ADD CONSTRAINT FK_TABLE_BOOK_REWARDS_TWO 
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_ORDER ADD CONSTRAINT FK_TABLE_ORDER_TABLE_CLIENT 
  FOREIGN KEY (CLIENT_ID) REFERENCES TABLE_CLIENT
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_ORDER_LIST ADD CONSTRAINT FK_TABLE_ORDER_LIST 
  FOREIGN KEY (ORDER_ID) REFERENCES TABLE_ORDER
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_ORDER_LIST ADD CONSTRAINT FK_TABLE_ORDER_LIST_TABLE_BOOK 
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_REVIEWS ADD CONSTRAINT FK_TABLE_REVIEWS_TABLE_BOOK 
  FOREIGN KEY (BOOK_ID) REFERENCES TABLE_BOOK
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE TABLE_REVIEWS ADD CONSTRAINT FK_TABLE_REVIEWS_TABLE_CLIENT 
  FOREIGN KEY (CLIENT_ID) REFERENCES TABLE_CLIENT
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

